# Generated by Django 2.2.1 on 2019-05-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0002_auto_20190510_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropsold',
            name='crop_weight',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='cropsold',
            name='sold',
            field=models.CharField(max_length=12),
        ),
    ]
