# Generated by Django 2.2.1 on 2019-05-09 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0002_auto_20190503_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(default=datetime.datetime.now)),
                ('crop_name', models.CharField(blank=True, max_length=20, null=True)),
                ('expenses_name', models.TextField()),
                ('expenses_amount', models.FloatField()),
                ('area', models.FloatField()),
                ('sold', models.FloatField(default=None, null=True)),
            ],
            options={
                'db_table': 'crop_entry',
            },
        ),
    ]
