# Generated by Django 2.2.1 on 2019-05-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0003_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='sold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
